name: Don

on:
  workflow_dispatch:
    inputs:
      who:
        description: 'What do you want?'
        type: choice
        required: true
        default: 'Mona'
        options:
          - Mona
          - Lisa
      when:
        description: 'When do you want it?'
        type: boolean
        required: false
        default: false 
jobs:
  job1:
    permissions: write-all # or write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
      - name: Show me
        run: echo "Hello, ${{ github.actor }}. You chose ${{ inputs.who }}."
      - name: Summary
        run: | 
          echo "You Selected ${{ inputs.who }}" >> $GITHUB_STEP_SUMMARY
          echo "{Who}=${{ inputs.who }}" >> $GITHUB_ENV
      - name: Makedir
        run: mkdir -p pwd/summary
      - name: Place File       
        run: echo ${{ inputs.who }} > pwd/summary/summary.txt
      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: pwd/summary/summary.txt   
          retention-days: 1
          overwrite: true
      - name: Create Release
        if: github.event.inputs.who == 'Lisa'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.sha }}
  job2:
    permissions: write-all # or write-all
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download Summary
        uses: actions/download-artifact@v4
        with:
          name: summary


            


