name: Don

on:
  workflow_dispatch:
    inputs:
      who:
        description: 'What do you want?'
        type: choice
        required: true
        default: 'Mona'
        options:
          - Mona
          - Lisa
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
      - name: Show me
        run: echo "Hello, ${{ github.actor }}. You chose ${{ inputs.who }}."
      - name: Summary
        run: echo ${{ inputs.who }} >> $GITHUB_STEP_SUMMARY
      - name: Makedir
        run: mkdir -p /pwd/summary
      - name: Place File       
        run: echo ${{ inputs.who }} > /pwd/summary/summary.txt
      - name: Upload Summary
        uses: actions/upload-artifact@v2
        with:
          name: summary
          path: /pwd/summary/summary.txt   


